# Generated by Django 4.2.4 on 2025-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_advertisement_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('writer', 'Writer'), ('editor', 'Editor'), ('admin', 'Admin'), ('ads_manager', 'Ads Manager')], default='user', max_length=15),
        ),
    ]
