# Generated by Django 4.2.4 on 2025-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('sidebar', 'Sidebar'), ('bottom', 'Bottom'), ('front', 'Front Page')], default='top', max_length=20),
        ),
    ]
