# Generated by Django 4.2.4 on 2025-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
