# Generated by Django 5.2 on 2025-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_advertisement_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('edit', 'Edit')], default='draft', max_length=15),
        ),
    ]
