# Generated by Django 5.2 on 2025-05-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_advertisement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
    ]
