# Generated by Django 5.2.1 on 2025-05-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_post_status'),
        ('newsapp', '0008_remove_advertisement_category'),
    ]

    operations = [
    ]
