# Generated by Django 5.2.1 on 2025-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_alter_category_options_rename_link_advertisement_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('edit', 'Edit')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('writer', 'Writer'), ('editor', 'Editor'), ('admin', 'Admin'), ('ads_manager', 'Ads Manager')], default='user', max_length=15),
        ),
    ]
